In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("08_investor_transactions.csv")
df

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,SIP,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,SIP,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,SIP,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [2]:
df.shape

(32778, 13)

In [14]:
df.info
df

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,NaT,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,NaT,119093,SIP,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,NaT,120504,SIP,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,NaT,148568,SIP,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,NaT,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [15]:
# 1. Fix Date Format
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    errors="coerce",
    dayfirst=True
)

In [16]:
# 2. Standardize Transaction Type
df["transaction_type"] = (
    df["transaction_type"]
    .astype(str)
    .str.strip()
    .str.lower()
)
mapping = {
    "sip": "SIP",
    "systematic investment plan": "SIP",
    "lumpsum": "Lumpsum",
    "lump sum": "Lumpsum",
    "purchase": "Lumpsum",
    "redemption": "Redemption",
    "redeem": "Redemption",
    "withdrawal": "Redemption"
}

df["transaction_type"] = df["transaction_type"].replace(mapping)

In [20]:
# 3. Validate Amount > 0
df["amount_inr"] = pd.to_numeric(df["amount_inr"], errors="coerce")

invalid_amounts = df[df["amount_inr"] <= 0]

print("\nInvalid Amount Records:", len(invalid_amounts))

df = df[df["amount_inr"] > 0]

Invalid Amount Records: 0

In [21]:
# 4. Validate KYC Status
valid_kyc = ["Verified", "Pending", "Rejected"]

df["kyc_status"] = (
    df["kyc_status"]
    .astype(str)
    .str.strip()
    .str.title()
)

invalid_kyc = df[~df["kyc_status"].isin(valid_kyc)]

print("Invalid KYC Records:", len(invalid_kyc))

Invalid KYC Records: 0

In [23]:
#To save cleaned csv
df.to_csv("C:/Users/DELL/OneDrive/Documents/projectIT/mutual-fund-analysis/data/processed/investor_transaction_clean.csv")
print("\Cleaned csv saved as")
print("C:/Users/DELL/OneDrive/Documents/projectIT/mutual-fund-analysis/data/processed/investor_transaction_clean.csv")

\Cleaned csv saved as
C:/Users/DELL/OneDrive/Documents/projectIT/mutual-fund-analysis/data/processed/investor_transaction_clean.csv